In [19]:
import numpy as np
import pandas as pd

In [20]:
df=pd.read_csv("Boston.csv")

In [21]:
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,CAT. MEDV,Unnamed: 15,Unnamed: 16
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0,0,NaN,NaN
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6,0,NaN,NaN
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7,1,NaN,NaN
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4,1,NaN,NaN
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2,1,NaN,NaN

In [22]:
df.isnull().sum()

CRIM             0
ZN               0
INDUS            0
CHAS             0
NOX              0
RM               0
AGE              0
DIS              0
RAD              0
TAX              0
PTRATIO          0
B                0
LSTAT            0
MEDV             0
CAT. MEDV        0
Unnamed: 15    506
Unnamed: 16    506
dtype: int64

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CRIM         506 non-null    float64
 1   ZN           506 non-null    float64
 2   INDUS        506 non-null    float64
 3   CHAS         506 non-null    int64
 4   NOX          506 non-null    float64
 5   RM           506 non-null    float64
 6   AGE          506 non-null    float64
 7   DIS          506 non-null    float64
 8   RAD          506 non-null    int64
 9   TAX          506 non-null    int64
 10  PTRATIO      506 non-null    float64
 11  B            506 non-null    float64
 12  LSTAT        506 non-null    float64
 13  MEDV         506 non-null    float64
 14  CAT. MEDV    506 non-null    int64
 15  Unnamed: 15  0 non-null      float64
 16  Unnamed: 16  0 non-null      float64
dtypes: float64(13), int64(4)
memory usage: 67.3 KB

In [24]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,CAT. MEDV,Unnamed: 15,Unnamed: 16
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,0.0,0.0
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806,0.166008,NaN,NaN
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104,0.372456,NaN,NaN
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000,0.000000,NaN,NaN
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000,0.000000,NaN,NaN
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000,0.000000,NaN,NaN
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000,0.000000,NaN,NaN
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000,1.000000,NaN,NaN

In [26]:
df.corr()['MEDV'].sort_values()

LSTAT         -0.737663
PTRATIO       -0.507787
INDUS         -0.483725
TAX           -0.468536
NOX           -0.427321
CRIM          -0.388305
RAD           -0.381626
AGE           -0.376955
CHAS           0.175260
DIS            0.249929
B              0.333461
ZN             0.360445
RM             0.695360
CAT. MEDV      0.789789
MEDV           1.000000
Unnamed: 15         NaN
Unnamed: 16         NaN
Name: MEDV, dtype: float64

In [28]:
x=df[['LSTAT','PTRATIO','RM','CAT. MEDV']]
y=df['MEDV']

In [29]:
x.head()

   LSTAT  PTRATIO     RM  CAT. MEDV
0   4.98     15.3  6.575          0
1   9.14     17.8  6.421          0
2   4.03     17.8  7.185          1
3   2.94     18.7  6.998          1
4   5.33     18.7  7.147          1

In [30]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: MEDV, dtype: float64

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [32]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [33]:
scaler.fit(x_train)

StandardScaler()

In [34]:
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [41]:
from keras.models import Sequential
from keras.layers import Dense

In [42]:
model=Sequential()

In [43]:
model.add(Dense(128,input_shape=(4,),activation='relu',name='input'))
model.add(Dense(64,activation='relu',name='layer'))
model.add(Dense(1,activation='linear',name='output'))
model.compile(optimizer='adam',loss='mse',metrics=['mae'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input (Dense)               (None, 128)               640

 layer (Dense)               (None, 64)                8256

 output (Dense)              (None, 1)                 65

=================================================================
Total params: 8,961
Trainable params: 8,961
Non-trainable params: 0
_________________________________________________________________

In [44]:
model.fit(x_train,y_train,epochs=100,validation_split=0.05)

Epoch 1/100
12/12 [==============================] - 1s 24ms/step - loss: 584.7919 - mae: 22.3565 - val_loss: 552.2886 - val_mae: 21.6619
Epoch 2/100
12/12 [==============================] - 0s 6ms/step - loss: 525.2821 - mae: 21.1951 - val_loss: 488.2623 - val_mae: 20.2192
Epoch 3/100
12/12 [==============================] - 0s 5ms/step - loss: 453.1761 - mae: 19.6468 - val_loss: 404.4524 - val_mae: 18.2462
Epoch 4/100
12/12 [==============================] - 0s 6ms/step - loss: 359.4767 - mae: 17.4221 - val_loss: 299.5764 - val_mae: 15.7660
Epoch 5/100
12/12 [==============================] - 0s 6ms/step - loss: 247.4256 - mae: 14.3482 - val_loss: 193.1523 - val_mae: 12.9047
Epoch 6/100
12/12 [==============================] - 0s 6ms/step - loss: 143.4193 - mae: 10.5910 - val_loss: 110.5091 - val_mae: 9.8275
Epoch 7/100
12/12 [==============================] - 0s 5ms/step - loss: 77.6159 - mae: 7.3882 - val_loss: 73.7562 - val_mae: 6.9732
Epoch 8/100
12/12 [==============================] - 0s 6ms/step - loss: 52.0504 - mae: 5.8541 - val_loss: 59.4152 - val_mae: 5.9300
Epoch 9/100
12/12 [==============================] - 0s 6ms/step - loss: 42.0826 - mae: 5.0809 - val_loss: 43.3891 - val_mae: 4.6179
Epoch 10/100
12/12 [==============================] - 0s 5ms/step - loss: 33.3823 - mae: 4.3444 - val_loss: 32.6176 - val_mae: 3.7958
Epoch 11/100
12/12 [==============================] - 0s 5ms/step - loss: 28.8649 - mae: 3.9444 - val_loss: 26.1194 - val_mae: 3.3872
Epoch 12/100
12/12 [==============================] - 0s 5ms/step - loss: 26.5085 - mae: 3.7302 - val_loss: 21.4179 - val_mae: 3.0202
Epoch 13/100
12/12 [==============================] - 0s 5ms/step - loss: 25.1963 - mae: 3.6363 - val_loss: 18.4988 - val_mae: 2.8670
Epoch 14/100
12/12 [==============================] - 0s 6ms/step - loss: 24.0739 - mae: 3.5569 - val_loss: 16.4628 - val_mae: 2.7779
Epoch 15/100
12/12 [==============================] - 0s 5ms/step - loss: 23.3817 - mae: 3.5129 - val_loss: 16.3559 - val_mae: 2.8131
Epoch 16/100
12/12 [==============================] - 0s 5ms/step - loss: 22.6145 - mae: 3.4655 - val_loss: 15.1683 - val_mae: 2.7581
Epoch 17/100
12/12 [==============================] - 0s 6ms/step - loss: 22.0140 - mae: 3.4195 - val_loss: 15.1634 - val_mae: 2.7786
Epoch 18/100
12/12 [==============================] - 0s 6ms/step - loss: 21.5368 - mae: 3.3927 - val_loss: 14.9613 - val_mae: 2.7888
Epoch 19/100
12/12 [==============================] - 0s 5ms/step - loss: 20.9284 - mae: 3.3563 - val_loss: 14.4709 - val_mae: 2.7451
Epoch 20/100
12/12 [==============================] - 0s 7ms/step - loss: 20.5593 - mae: 3.3282 - val_loss: 14.6134 - val_mae: 2.7634
Epoch 21/100
12/12 [==============================] - 0s 7ms/step - loss: 20.2213 - mae: 3.3157 - val_loss: 14.5488 - val_mae: 2.7731
Epoch 22/100
12/12 [==============================] - 0s 7ms/step - loss: 19.7568 - mae: 3.2738 - val_loss: 14.3078 - val_mae: 2.7478
Epoch 23/100
12/12 [==============================] - 0s 8ms/step - loss: 19.4101 - mae: 3.2399 - val_loss: 13.0513 - val_mae: 2.6595
Epoch 24/100
12/12 [==============================] - 0s 8ms/step - loss: 19.0181 - mae: 3.2289 - val_loss: 13.1129 - val_mae: 2.6731
Epoch 25/100
12/12 [==============================] - 0s 7ms/step - loss: 18.7607 - mae: 3.2253 - val_loss: 12.8939 - val_mae: 2.6605
Epoch 26/100
12/12 [==============================] - 0s 12ms/step - loss: 18.4371 - mae: 3.1988 - val_loss: 12.9556 - val_mae: 2.6497
Epoch 27/100
12/12 [==============================] - 0s 8ms/step - loss: 18.1605 - mae: 3.1762 - val_loss: 12.6494 - val_mae: 2.6252
Epoch 28/100
12/12 [==============================] - 0s 5ms/step - loss: 17.8716 - mae: 3.1527 - val_loss: 11.8557 - val_mae: 2.5550
Epoch 29/100
12/12 [==============================] - 0s 6ms/step - loss: 17.8036 - mae: 3.1502 - val_loss: 12.2783 - val_mae: 2.6027
Epoch 30/100
12/12 [==============================] - 0s 6ms/step - loss: 17.3928 - mae: 3.1352 - val_loss: 12.3486 - val_mae: 2.6066
Epoch 31/100
12/12 [==============================] - 0s 6ms/step - loss: 17.4328 - mae: 3.1634 - val_loss: 12.4698 - val_mae: 2.6198
Epoch 32/100
12/12 [==============================] - 0s 6ms/step - loss: 16.9666 - mae: 3.1054 - val_loss: 11.3065 - val_mae: 2.5161
Epoch 33/100
12/12 [==============================] - 0s 6ms/step - loss: 16.7687 - mae: 3.0976 - val_loss: 12.0509 - val_mae: 2.5801
Epoch 34/100
12/12 [==============================] - 0s 6ms/step - loss: 16.5186 - mae: 3.0885 - val_loss: 12.1562 - val_mae: 2.5818
Epoch 35/100
12/12 [==============================] - 0s 6ms/step - loss: 16.4388 - mae: 3.0789 - val_loss: 11.3537 - val_mae: 2.4891
Epoch 36/100
12/12 [==============================] - 0s 5ms/step - loss: 16.0576 - mae: 3.0412 - val_loss: 11.3339 - val_mae: 2.4839
Epoch 37/100
12/12 [==============================] - 0s 6ms/step - loss: 16.1814 - mae: 3.0261 - val_loss: 10.8050 - val_mae: 2.4384
Epoch 38/100
12/12 [==============================] - 0s 6ms/step - loss: 15.8565 - mae: 2.9902 - val_loss: 10.2103 - val_mae: 2.3612
Epoch 39/100
12/12 [==============================] - 0s 6ms/step - loss: 15.6111 - mae: 2.9775 - val_loss: 9.7312 - val_mae: 2.3301
Epoch 40/100
12/12 [==============================] - 0s 6ms/step - loss: 15.6386 - mae: 2.9739 - val_loss: 9.9748 - val_mae: 2.3312
Epoch 41/100
12/12 [==============================] - 0s 6ms/step - loss: 15.3333 - mae: 2.9572 - val_loss: 9.8050 - val_mae: 2.3208
Epoch 42/100
12/12 [==============================] - 0s 6ms/step - loss: 15.2554 - mae: 2.9537 - val_loss: 9.8635 - val_mae: 2.3404
Epoch 43/100
12/12 [==============================] - 0s 6ms/step - loss: 15.0786 - mae: 2.9504 - val_loss: 10.3247 - val_mae: 2.3450
Epoch 44/100
12/12 [==============================] - 0s 6ms/step - loss: 14.9350 - mae: 2.9419 - val_loss: 10.0320 - val_mae: 2.3440
Epoch 45/100
12/12 [==============================] - 0s 11ms/step - loss: 14.8711 - mae: 2.9123 - val_loss: 9.2482 - val_mae: 2.3442
Epoch 46/100
12/12 [==============================] - 0s 6ms/step - loss: 14.8652 - mae: 2.9083 - val_loss: 9.2897 - val_mae: 2.3501
Epoch 47/100
12/12 [==============================] - 0s 6ms/step - loss: 14.6015 - mae: 2.8954 - val_loss: 9.7560 - val_mae: 2.3330
Epoch 48/100
12/12 [==============================] - 0s 6ms/step - loss: 14.5076 - mae: 2.8888 - val_loss: 9.4879 - val_mae: 2.3111
Epoch 49/100
12/12 [==============================] - 0s 6ms/step - loss: 14.4172 - mae: 2.8964 - val_loss: 10.1882 - val_mae: 2.3507
Epoch 50/100
12/12 [==============================] - 0s 6ms/step - loss: 14.3439 - mae: 2.8839 - val_loss: 9.2951 - val_mae: 2.3238
Epoch 51/100
12/12 [==============================] - 0s 6ms/step - loss: 14.2432 - mae: 2.8686 - val_loss: 9.1674 - val_mae: 2.2745
Epoch 52/100
12/12 [==============================] - 0s 5ms/step - loss: 14.1809 - mae: 2.8732 - val_loss: 9.4830 - val_mae: 2.2899
Epoch 53/100
12/12 [==============================] - 0s 6ms/step - loss: 14.0488 - mae: 2.8630 - val_loss: 9.4363 - val_mae: 2.2809
Epoch 54/100
12/12 [==============================] - 0s 5ms/step - loss: 13.9603 - mae: 2.8409 - val_loss: 9.9815 - val_mae: 2.4168
Epoch 55/100
12/12 [==============================] - 0s 5ms/step - loss: 13.8606 - mae: 2.8325 - val_loss: 9.6595 - val_mae: 2.3555
Epoch 56/100
12/12 [==============================] - 0s 5ms/step - loss: 13.7579 - mae: 2.8308 - val_loss: 9.1370 - val_mae: 2.2870
Epoch 57/100
12/12 [==============================] - 0s 5ms/step - loss: 13.7894 - mae: 2.8481 - val_loss: 8.8841 - val_mae: 2.2399
Epoch 58/100
12/12 [==============================] - 0s 5ms/step - loss: 13.6080 - mae: 2.8147 - val_loss: 8.6297 - val_mae: 2.2939
Epoch 59/100
12/12 [==============================] - 0s 5ms/step - loss: 13.5243 - mae: 2.8044 - val_loss: 8.7218 - val_mae: 2.2824
Epoch 60/100
12/12 [==============================] - 0s 5ms/step - loss: 13.4033 - mae: 2.7989 - val_loss: 9.2786 - val_mae: 2.2786
Epoch 61/100
12/12 [==============================] - 0s 5ms/step - loss: 13.4010 - mae: 2.8159 - val_loss: 9.6182 - val_mae: 2.3248
Epoch 62/100

12/12 [==============================] - 0s 5ms/step - loss: 13.2213 - mae: 2.7942 - val_loss: 8.7343 - val_mae: 2.2711
Epoch 63/100
12/12 [==============================] - 0s 5ms/step - loss: 13.2067 - mae: 2.7635 - val_loss: 8.1367 - val_mae: 2.2080
Epoch 64/100
12/12 [==============================] - 0s 5ms/step - loss: 13.2038 - mae: 2.7910 - val_loss: 8.9881 - val_mae: 2.1999
Epoch 65/100
12/12 [==============================] - 0s 5ms/step - loss: 13.0616 - mae: 2.7842 - val_loss: 8.5524 - val_mae: 2.2204
Epoch 66/100
12/12 [==============================] - 0s 5ms/step - loss: 12.8417 - mae: 2.7362 - val_loss: 7.6255 - val_mae: 2.1572
Epoch 67/100
12/12 [==============================] - 0s 5ms/step - loss: 13.0971 - mae: 2.7400 - val_loss: 7.2103 - val_mae: 2.0925
Epoch 68/100
12/12 [==============================] - 0s 5ms/step - loss: 12.8611 - mae: 2.7247 - val_loss: 7.5385 - val_mae: 2.1021
Epoch 69/100
12/12 [==============================] - 0s 5ms/step - loss: 12.7731 - mae: 2.7529 - val_loss: 8.7343 - val_mae: 2.2158
Epoch 70/100
12/12 [==============================] - 0s 5ms/step - loss: 12.6096 - mae: 2.7352 - val_loss: 8.4358 - val_mae: 2.3035
Epoch 71/100
12/12 [==============================] - 0s 5ms/step - loss: 12.7282 - mae: 2.7490 - val_loss: 9.0149 - val_mae: 2.2940
Epoch 72/100
12/12 [==============================] - 0s 5ms/step - loss: 12.5222 - mae: 2.7365 - val_loss: 8.5894 - val_mae: 2.2864
Epoch 73/100
12/12 [==============================] - 0s 5ms/step - loss: 12.5352 - mae: 2.7039 - val_loss: 7.8834 - val_mae: 2.2131
Epoch 74/100
12/12 [==============================] - 0s 5ms/step - loss: 12.4499 - mae: 2.7083 - val_loss: 8.5421 - val_mae: 2.1997
Epoch 75/100
12/12 [==============================] - 0s 5ms/step - loss: 12.3609 - mae: 2.7224 - val_loss: 7.9552 - val_mae: 2.1682
Epoch 76/100
12/12 [==============================] - 0s 5ms/step - loss: 12.1894 - mae: 2.6729 - val_loss: 8.0768 - val_mae: 2.2053
Epoch 77/100
12/12 [==============================] - 0s 5ms/step - loss: 12.2779 - mae: 2.6950 - val_loss: 7.9165 - val_mae: 2.1356
Epoch 78/100
12/12 [==============================] - 0s 5ms/step - loss: 12.1958 - mae: 2.6833 - val_loss: 7.9626 - val_mae: 2.2022
Epoch 79/100
12/12 [==============================] - 0s 5ms/step - loss: 12.1576 - mae: 2.6749 - val_loss: 7.3975 - val_mae: 2.0911
Epoch 80/100
12/12 [==============================] - 0s 5ms/step - loss: 12.0700 - mae: 2.6425 - val_loss: 7.2763 - val_mae: 2.1067
Epoch 81/100
12/12 [==============================] - 0s 5ms/step - loss: 11.9667 - mae: 2.6527 - val_loss: 8.0577 - val_mae: 2.1735
Epoch 82/100
12/12 [==============================] - 0s 5ms/step - loss: 12.1378 - mae: 2.6646 - val_loss: 8.1218 - val_mae: 2.1952
Epoch 83/100
12/12 [==============================] - 0s 5ms/step - loss: 11.8875 - mae: 2.6434 - val_loss: 7.4236 - val_mae: 2.1257
Epoch 84/100
12/12 [==============================] - 0s 5ms/step - loss: 12.0687 - mae: 2.6811 - val_loss: 8.6329 - val_mae: 2.2137
Epoch 85/100
12/12 [==============================] - 0s 5ms/step - loss: 11.8365 - mae: 2.6398 - val_loss: 8.3917 - val_mae: 2.3250
Epoch 86/100
12/12 [==============================] - 0s 5ms/step - loss: 11.7617 - mae: 2.6333 - val_loss: 8.3061 - val_mae: 2.1892
Epoch 87/100
12/12 [==============================] - 0s 5ms/step - loss: 11.5916 - mae: 2.6318 - val_loss: 7.8998 - val_mae: 2.1322
Epoch 88/100
12/12 [==============================] - 0s 5ms/step - loss: 11.6200 - mae: 2.6362 - val_loss: 7.6290 - val_mae: 2.1251
Epoch 89/100
12/12 [==============================] - 0s 6ms/step - loss: 11.7720 - mae: 2.6054 - val_loss: 6.7896 - val_mae: 2.0552
Epoch 90/100
12/12 [==============================] - 0s 5ms/step - loss: 11.6295 - mae: 2.6370 - val_loss: 8.0934 - val_mae: 2.0964
Epoch 91/100
12/12 [==============================] - 0s 5ms/step - loss: 11.4258 - mae: 2.6238 - val_loss: 7.8926 - val_mae: 2.1669
Epoch 92/100
12/12 [==============================] - 0s 5ms/step - loss: 11.6286 - mae: 2.6027 - val_loss: 7.7763 - val_mae: 2.1888
Epoch 93/100
12/12 [==============================] - 0s 5ms/step - loss: 11.2948 - mae: 2.5965 - val_loss: 7.9220 - val_mae: 2.1486
Epoch 94/100
12/12 [==============================] - 0s 5ms/step - loss: 11.2683 - mae: 2.5951 - val_loss: 7.6029 - val_mae: 2.1374
Epoch 95/100
12/12 [==============================] - 0s 5ms/step - loss: 11.2332 - mae: 2.5944 - val_loss: 7.2323 - val_mae: 2.0521
Epoch 96/100
12/12 [==============================] - 0s 5ms/step - loss: 11.0952 - mae: 2.5743 - val_loss: 7.3326 - val_mae: 2.1009
Epoch 97/100
12/12 [==============================] - 0s 6ms/step - loss: 10.9982 - mae: 2.5612 - val_loss: 7.4019 - val_mae: 2.0879
Epoch 98/100
12/12 [==============================] - 0s 6ms/step - loss: 11.0920 - mae: 2.5802 - val_loss: 7.5105 - val_mae: 2.0694
Epoch 99/100
12/12 [==============================] - 0s 5ms/step - loss: 10.9615 - mae: 2.5448 - val_loss: 6.7356 - val_mae: 2.0093
Epoch 100/100
12/12 [==============================] - 0s 5ms/step - loss: 10.9112 - mae: 2.5386 - val_loss: 6.8705 - val_mae: 1.9858

In [45]:
model.evaluate(x_test,y_test)

4/4 [==============================] - 0s 2ms/step - loss: 12.0344 - mae: 2.6841

[12.034439086914062, 2.6840837001800537]